#!/bin/sh
set -e
umask 007

PATH=/home/mjh22/groggs/bin/Linux:/home/mjh22/groggs/sbin:/usr/local/bin:$PATH
export PATH

cd /home/mjh22/groggs/spool
lockfile secretseed /home/mjh22/groggs/lib/server/updatesecret

# This is free software; may redistribute it and/or modify it under
# the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is made available in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in the top-
# level src directory.  Alternatively could write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 
