#!/bin/sh
# This is free software; may redistribute it and/or modify it under
# the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is made available in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in the top-
# level src directory.  Alternatively could write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 

set -e
umask 007
maxrand=1024
cd secret-tmp
rm -f ./* 2>/dev/null || true
cp ../log/log log
ls -al ../secretseed
cat log ../secretseed | \
  des -E -k 'General Purpose Reverse Ordered Gossip Gathering System' \
  >all
perl -0777 -e '
  $keeplen= (stat("../secretseed"))[7];
  $keeplen>0 || die $!;
  $keeplen += 32;
  $keeplen = '$maxrand' if $keeplen > '$maxrand';
  open(O,"all") || die $!;
  $d=<O>;
  $v=substr($d,length($d)-$keeplen);
  length($v) == $keeplen || die $!;
  open(V,"+< ../secretseed") || die $!;
  print V $v || die $!;
  close(V) || die $!;
'
rm -f ./* 2>/dev/null || true
ls -al ../secretseed
