#!/bin/sh

set -e
PATH=/home/mjh22/groggs/sbin:/usr/local/bin:$PATH
export PATH

cd /home/mjh22/groggs/spool
umask 007

# This is free software; may redistribute it and/or modify it under
# the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is made available in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in the top-
# level src directory.  Alternatively could write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 

test -f userdatabase.1 && gzip -9 userdatabase.1

set 7 6 5 4 3 2 1

while test $# -gt 1
do
	test -f userdatabase.$2.gz && mv userdatabase.$2.gz userdatabase.$1.gz
	shift
done

lockfile ./userdatabase 'cp userdatabase userdatabase.1'
